shhh <- suppressPackageStartupMessages

shhh(library(shiny))
shhh(library(dplyr))
shhh(library(tidyr))
shhh(library(purrr))
shhh(library(readr))
shhh(library(shinydashboard))
shhh(library(shinydashboardPlus))
shhh(library(shinyWidgets))
shhh(library(shinycssloaders))
shhh(library(shinybusy))
shhh(library(shinyjs))
shhh(library(htmlwidgets))
shhh(library(rintrojs))
shhh(library(config))
shhh(library(CUSOMShinyHelpers))
